language: node_js
node_js: '13'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '13'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'bTeAMpxifrzpDTr/Oys6efdAo5XNNV5mXUPE9DhlxMUHdKMAysFDe685xG5zzruSG1f8vdSpXLeu3zzLY3d83+itdNvUQw2dGNWbpeihyaSnPAp2U0b6hxNSFV0aT8lSJySZqgDO0ey+UcUh/VE6gP+5zGL6qUWn/FO86vG5wLv3simOiXQbR+yXVAcbXB1dkh+d65C7wHfVzLgW03fp9Zcj0esaUMaJqBKX70QOI7oiBCr/4PL7uG/OrqgJe/ilWp+R8kzoVm7uDmQCo+IoUU8/N72A5pQmAaBXDytoDvWbJ1IMoDwwos4EZDi8zIFY4RqpuTk0P9S1jdQy/Ubu2QTrjHkTeRM6lBBMJZ6dN9pYgoXsYIMk5taTV74gbRpuZz2lWwuuNJY4p3KsDM2MesXIEi+DXHv2pKf0bbMMPzVRa587stw/Csu2ZqL+3j1qmOjyIfwXxjY4M3QH8RocNiEGIe7gNS4EncoFCK8ml3GbRq74xiK1Fg4ZgxS3z3SoibYiQGKoGo6RXARoNfyEX7FDo/9Dw5yP9DSpCrSRLPrj8m1VuXCz6hPi1rutr8p2XSmVOLxEsrQCPlwLcJs8ozNrcKJqHqW+oaXdD1CisogztRHhxO1uIRK1ktJfEevdVVVDz5dqvOt2Zp3umFW9EMCpcD5f+CHTCF2RhFvswYY='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.

# nyc does not work because it monkey patches `child_process.spawn()` and forces
# `node` to be `process.execPath` (the `node` that spawned `nyc`, i.e. the
# global `node`) by modifying the `$PATH` environment variable.
# TODO: This should be fixed with nyc@15
# See https://github.com/istanbuljs/spawn-wrap/issues/108
env:
  COVERAGE: 'false'
